#!/bin/bash

case $# in
    0)
        read -p "user: " user
        read -p "repo: " repo
        ;;
    1)
        both=$1
        ;;
    2)
        user=$1
        repo=$2
        ;;
    *)
        exit
        ;;
esac

if [[ -n $user && -n $repo ]]; then
    git=$user/$repo.git
fi

if [[ -n $both ]]; then
    git=$both.git
fi

git clone git@github.com:$git
