#!/bin/bash

case $# in
    0)
        read -p "user: " user
        read -p "repo: " repo
        ;;
    1)
        BOTH=$1
        ;;
    2)
        USER=$1
        REPO=$2
        ;;
    *)
        exit
        ;;
esac

if [[ -n $USER && -n $REPO ]]; then
    GIT=$USER/$REPO.git
fi

if [[ -n $BOTH ]]; then
    GIT=$BOTH.git
fi

git clone git@github.com:$GIT
