#!/bin/bash

if [[ $# -lt 2 ]]; then
    BIN=$(get-file-full-path $0)

    echo "Usage: $BIN <url>"
    echo "e.g. $BIN https://discord.com/api/download?platform=linux&format=deb"

    exit 1
fi

URL=$1

DEB=$(mktemp --suffix=.deb)

curl -L -o $DEB $URL

sudo apt install $DEB
