#!/bin/bash

if [[ $# -lt 1 || $1 -lt 1 || $1 -gt 100 ]]; then
    BIN=$(get-file-full-path $0)

    echo "Usage: $BIN <1-100>"
    echo "e.g. $BIN 50"

    exit 1
fi

PERCENTAGE=$1

MAX=$(cat /sys/class/backlight/intel_backlight/max_brightness | sed 's/\n//')

BRIGHTNESS=$(echo "($PERCENTAGE / 100) * $MAX" | bc -l | awk '{printf "%d\n", $1}')

echo $BRIGHTNESS | sudo tee /sys/class/backlight/intel_backlight/brightness > /dev/null
