#!/usr/bin/env bash

# export dotfile from home dir to cstiago/dotfiles repo, replacing it

dotfiles=($@)

if [[ $# -eq 0 ]]; then
    read -p "dotfile: " dotfile
    dotfiles=($dotfile)
fi

for dotfile in $dotfiles; do
    cp $HOME/$dotfile $DFTERMUX
done
