#!/bin/bash

if [[ ! -f $DEBREPOLIST ]]; then
    echo "deb [trusted=yes] file:$DEBREPODIR ./" | sudo tee $DEBREPOLIST
fi

sudo mkdir -p $DEBREPODIR
cd $DEBREPODIR
sudo ln -fs $DEBREPOTXT .
sudo rm ./*.deb

sudo awk '{print $1, $2}' $DEBREPOTXT | xargs -n 2 bash -c 'sudo curl -L -o "$1/$2.deb" "$3"' bash $DEBREPODIR

sudo dpkg-scanpackages . /dev/null | sudo gzip -9c | sudo tee $DEBREPODIR/Packages.gz > /dev/null

sudo apt update
